# Generated by Django 3.2.4 on 2021-07-08 19:01

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerextend',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('university_name', models.CharField(max_length=500)),
                ('university_image', models.CharField(blank=True, max_length=10000)),
                ('university_latitude', models.FloatField()),
                ('university_longitude', models.FloatField()),
                ('profile_photo', models.ImageField(blank=True, upload_to=registration.models.get_upload_path)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('personal_description', models.CharField(blank=True, max_length=200, null=True)),
                ('personality_tags', models.CharField(max_length=200, null=True)),
                ('sharing_preferences', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('flat_finder', models.CharField(max_length=20)),
                ('admission', models.CharField(max_length=20)),
                ('food_preferences', models.CharField(max_length=20)),
                ('cooking_skills', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
