# Generated by Django 3.2.4 on 2021-07-07 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerextend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to=registration.models.get_upload_path)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('personal_description', models.CharField(max_length=200, null=True)),
                ('personality_tags', models.CharField(max_length=200, null=True)),
                ('prospective_university', models.CharField(max_length=20)),
                ('sharing_preferences', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('flat_finder', models.CharField(max_length=20)),
                ('admission', models.CharField(max_length=20)),
                ('food_preferences', models.CharField(max_length=20)),
                ('cooking_skills', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
