# Generated by Django 3.2.4 on 2021-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registerextend_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerextend',
            name='personal_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
